### ISSUE TITLE
profile.encode not a function

### ISSUE THREAD

**Issue by f0ster** [saadtazi/firefox-profile-js#63]
I have firefox installed on ubuntu, and I get the following error, 
```
TypeError: profile.encode is not a function
    at Driver (/usr/src/app/selenium_wd_tests/node_modules/selenium-webdriver/firefox/index.js:486:46)
    at Builder.build (/usr/src/app/selenium_wd_tests/node_modules/selenium-webdriver/index.js:549:16)
    at /usr/src/app/selenium_wd_tests/basic.js:30:23
    at /usr/src/app/selenium_wd_tests/node_modules/firefox-profile/lib/firefox_profile.js:427:7
    at /usr/src/app/selenium_wd_tests/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
```

Simple test case below

```
 /******************************************************************
     * with selenium webdriverJs
     * installs firebug 
     * and make http://saadtazi.com the url that is opened on new tabs
    /******************************************************************/
    var webdriver = require('selenium-webdriver');
 
    // create profile 
    var FirefoxProfile = require('firefox-profile');
    var myProfile = new FirefoxProfile();
 
    // you can add an extension by specifying the path to the xpi file  
    // or to the unzipped extension directory 
   // myProfile.addExtension('test/extensions/firebug-1.12.4-fx.xpi', function() {
        
        var capabilities = webdriver.Capabilities.firefox();
 
        // you can set firefox preferences BEFORE calling encoded() 
        myProfile.setPreference('browser.newtab.url', 'http://saadtazi.com');
        
        // attach your newly created profile 
        
        myProfile.encoded(function(encodedProfile) {
            capabilities.set('firefox_profile', encodedProfile);
 
            
            // start the browser 
            var wd = new webdriver.Builder().
                      withCapabilities(capabilities).
                      build();
            
            // woot! 
            wd.get('http://en.wikipedia.org');
        });
   // });
```

**Comment by f0ster** [comment]
I got mine working by locking down the following versions, 
```
     "firefox-profile": "0.4.0",
    "selenium-webdriver": "2.53.3",
```

**Comment by saadtazi** [comment]
Oops, that was too fast for me ;).
